# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created: Mon Apr 21 16:30:42 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProvWindow(object):
    def setupUi(self, ProvWindow):
        ProvWindow.setObjectName(_fromUtf8("ProvWindow"))
        ProvWindow.resize(1004, 592)
        self.widget = QtGui.QWidget(ProvWindow)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.mainlayout = QtGui.QHBoxLayout(self.widget)
        self.mainlayout.setSpacing(6)
        self.mainlayout.setContentsMargins(1, -1, -1, -1)
        self.mainlayout.setObjectName(_fromUtf8("mainlayout"))
        self.tab = QtGui.QTabWidget(self.widget)
        self.tab.setTabPosition(QtGui.QTabWidget.West)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.mainTab = QtGui.QWidget()
        self.mainTab.setObjectName(_fromUtf8("mainTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mainTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.mainTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spinBoxDepth = QtGui.QSpinBox(self.mainTab)
        self.spinBoxDepth.setObjectName(_fromUtf8("spinBoxDepth"))
        self.horizontalLayout_4.addWidget(self.spinBoxDepth)
        self.checkBoxShowAll = QtGui.QCheckBox(self.mainTab)
        self.checkBoxShowAll.setObjectName(_fromUtf8("checkBoxShowAll"))
        self.horizontalLayout_4.addWidget(self.checkBoxShowAll)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_2 = QtGui.QLabel(self.mainTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxShowFile = QtGui.QCheckBox(self.mainTab)
        self.checkBoxShowFile.setObjectName(_fromUtf8("checkBoxShowFile"))
        self.horizontalLayout_3.addWidget(self.checkBoxShowFile)
        self.checkBoxShowProc = QtGui.QCheckBox(self.mainTab)
        self.checkBoxShowProc.setObjectName(_fromUtf8("checkBoxShowProc"))
        self.horizontalLayout_3.addWidget(self.checkBoxShowProc)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_3 = QtGui.QLabel(self.mainTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.checkBoxCommonFilter = QtGui.QCheckBox(self.mainTab)
        self.checkBoxCommonFilter.setObjectName(_fromUtf8("checkBoxCommonFilter"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBoxCommonFilter)
        self.checkBoxTempFilter = QtGui.QCheckBox(self.mainTab)
        self.checkBoxTempFilter.setObjectName(_fromUtf8("checkBoxTempFilter"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBoxTempFilter)
        self.lineEditTempFilter = QtGui.QLineEdit(self.mainTab)
        self.lineEditTempFilter.setObjectName(_fromUtf8("lineEditTempFilter"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditTempFilter)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.content = QtGui.QLabel(self.mainTab)
        self.content.setMinimumSize(QtCore.QSize(300, 0))
        self.content.setMaximumSize(QtCore.QSize(300, 16777215))
        self.content.setWordWrap(True)
        self.content.setObjectName(_fromUtf8("content"))
        self.verticalLayout_2.addWidget(self.content)
        self.contentGraph = PlotWidget(self.mainTab)
        self.contentGraph.setObjectName(_fromUtf8("contentGraph"))
        self.verticalLayout_2.addWidget(self.contentGraph)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonEnableEditor = QtGui.QPushButton(self.mainTab)
        self.pushButtonEnableEditor.setObjectName(_fromUtf8("pushButtonEnableEditor"))
        self.horizontalLayout.addWidget(self.pushButtonEnableEditor)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 15)
        self.verticalLayout_2.setStretch(2, 30)
        self.verticalLayout_2.setStretch(3, 1)
        self.tab.addTab(self.mainTab, _fromUtf8(""))
        self.editTab = QtGui.QWidget()
        self.editTab.setObjectName(_fromUtf8("editTab"))
        self.formLayout_3 = QtGui.QFormLayout(self.editTab)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.editTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit = QtGui.QLineEdit(self.editTab)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_6 = QtGui.QLabel(self.editTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_2 = QtGui.QLineEdit(self.editTab)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_7 = QtGui.QLabel(self.editTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_3 = QtGui.QLineEdit(self.editTab)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_8 = QtGui.QLabel(self.editTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_4 = QtGui.QLineEdit(self.editTab)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_9 = QtGui.QLabel(self.editTab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.editTab)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.plainTextEdit)
        self.label_10 = QtGui.QLabel(self.editTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_10)
        self.tableWidget = QtGui.QTableWidget(self.editTab)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.tableWidget)
        self.pushButtonReExecute = QtGui.QPushButton(self.editTab)
        self.pushButtonReExecute.setObjectName(_fromUtf8("pushButtonReExecute"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.pushButtonReExecute)
        self.tab.addTab(self.editTab, _fromUtf8(""))
        self.filterTab = QtGui.QWidget()
        self.filterTab.setObjectName(_fromUtf8("filterTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.filterTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.filterTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.pushButtonResetFilter = QtGui.QPushButton(self.filterTab)
        self.pushButtonResetFilter.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButtonResetFilter.setObjectName(_fromUtf8("pushButtonResetFilter"))
        self.horizontalLayout_5.addWidget(self.pushButtonResetFilter)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.textEditFilter = QtGui.QTextEdit(self.filterTab)
        self.textEditFilter.setObjectName(_fromUtf8("textEditFilter"))
        self.verticalLayout.addWidget(self.textEditFilter)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButtonSaveFilter = QtGui.QPushButton(self.filterTab)
        self.pushButtonSaveFilter.setObjectName(_fromUtf8("pushButtonSaveFilter"))
        self.horizontalLayout_7.addWidget(self.pushButtonSaveFilter)
        self.pushButtonRestoreFilter = QtGui.QPushButton(self.filterTab)
        self.pushButtonRestoreFilter.setObjectName(_fromUtf8("pushButtonRestoreFilter"))
        self.horizontalLayout_7.addWidget(self.pushButtonRestoreFilter)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.tab.addTab(self.filterTab, _fromUtf8(""))
        self.mainlayout.addWidget(self.tab)
        self.graphTab = QtGui.QTabWidget(self.widget)
        self.graphTab.setObjectName(_fromUtf8("graphTab"))
        self.provTab = QtGui.QWidget()
        self.provTab.setObjectName(_fromUtf8("provTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.provTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonBack = QtGui.QPushButton(self.provTab)
        self.pushButtonBack.setObjectName(_fromUtf8("pushButtonBack"))
        self.horizontalLayout_2.addWidget(self.pushButtonBack)
        self.pushButtonForward = QtGui.QPushButton(self.provTab)
        self.pushButtonForward.setObjectName(_fromUtf8("pushButtonForward"))
        self.horizontalLayout_2.addWidget(self.pushButtonForward)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.graph = GraphWidget(self.provTab)
        self.graph.setObjectName(_fromUtf8("graph"))
        self.verticalLayout_3.addWidget(self.graph)
        self.graphTab.addTab(self.provTab, _fromUtf8(""))
        self.statsTab = QtGui.QWidget()
        self.statsTab.setObjectName(_fromUtf8("statsTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.statsTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBoxGraphCPU = QtGui.QCheckBox(self.statsTab)
        self.checkBoxGraphCPU.setObjectName(_fromUtf8("checkBoxGraphCPU"))
        self.horizontalLayout_6.addWidget(self.checkBoxGraphCPU)
        self.checkBoxGraphMem = QtGui.QCheckBox(self.statsTab)
        self.checkBoxGraphMem.setObjectName(_fromUtf8("checkBoxGraphMem"))
        self.horizontalLayout_6.addWidget(self.checkBoxGraphMem)
        self.checkBoxGraphIO = QtGui.QCheckBox(self.statsTab)
        self.checkBoxGraphIO.setObjectName(_fromUtf8("checkBoxGraphIO"))
        self.horizontalLayout_6.addWidget(self.checkBoxGraphIO)
        self.checkBoxGraphThread = QtGui.QCheckBox(self.statsTab)
        self.checkBoxGraphThread.setObjectName(_fromUtf8("checkBoxGraphThread"))
        self.horizontalLayout_6.addWidget(self.checkBoxGraphThread)
        self.checkBoxGraphNetwork = QtGui.QCheckBox(self.statsTab)
        self.checkBoxGraphNetwork.setObjectName(_fromUtf8("checkBoxGraphNetwork"))
        self.horizontalLayout_6.addWidget(self.checkBoxGraphNetwork)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.fullStatsGraph = PlotWidget(self.statsTab)
        self.fullStatsGraph.setObjectName(_fromUtf8("fullStatsGraph"))
        self.verticalLayout_5.addWidget(self.fullStatsGraph)
        self.graphTab.addTab(self.statsTab, _fromUtf8(""))
        self.mainlayout.addWidget(self.graphTab)
        self.mainlayout.setStretch(0, 5)
        self.mainlayout.setStretch(1, 20)
        ProvWindow.setCentralWidget(self.widget)
        self.menubar = QtGui.QMenuBar(ProvWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuProvenance = QtGui.QMenu(self.menubar)
        self.menuProvenance.setObjectName(_fromUtf8("menuProvenance"))
        ProvWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ProvWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ProvWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(ProvWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(ProvWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.action = QtGui.QAction(ProvWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.actionQuit = QtGui.QAction(ProvWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHelp = QtGui.QAction(ProvWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(ProvWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action_SOLE = QtGui.QAction(ProvWindow)
        self.action_SOLE.setObjectName(_fromUtf8("action_SOLE"))
        self.action_PTU = QtGui.QAction(ProvWindow)
        self.action_PTU.setObjectName(_fromUtf8("action_PTU"))
        self.action_GUI = QtGui.QAction(ProvWindow)
        self.action_GUI.setObjectName(_fromUtf8("action_GUI"))
        self.actionRefresh = QtGui.QAction(ProvWindow)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionBack = QtGui.QAction(ProvWindow)
        self.actionBack.setObjectName(_fromUtf8("actionBack"))
        self.actionForward = QtGui.QAction(ProvWindow)
        self.actionForward.setObjectName(_fromUtf8("actionForward"))
        self.actionOpen_Provenance = QtGui.QAction(ProvWindow)
        self.actionOpen_Provenance.setObjectName(_fromUtf8("actionOpen_Provenance"))
        self.actionCopy_ID = QtGui.QAction(ProvWindow)
        self.actionCopy_ID.setObjectName(_fromUtf8("actionCopy_ID"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Provenance)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionRefresh)
        self.menuView.addAction(self.actionBack)
        self.menuView.addAction(self.actionForward)
        self.menuSettings.addAction(self.action_SOLE)
        self.menuSettings.addAction(self.action_PTU)
        self.menuSettings.addAction(self.action_GUI)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuProvenance.addAction(self.actionCopy_ID)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProvenance.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ProvWindow)
        self.tab.setCurrentIndex(2)
        self.graphTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProvWindow)
        ProvWindow.setTabOrder(self.spinBoxDepth, self.checkBoxShowAll)
        ProvWindow.setTabOrder(self.checkBoxShowAll, self.checkBoxShowFile)
        ProvWindow.setTabOrder(self.checkBoxShowFile, self.checkBoxShowProc)
        ProvWindow.setTabOrder(self.checkBoxShowProc, self.lineEditTempFilter)
        ProvWindow.setTabOrder(self.lineEditTempFilter, self.checkBoxTempFilter)
        ProvWindow.setTabOrder(self.checkBoxTempFilter, self.checkBoxCommonFilter)
        ProvWindow.setTabOrder(self.checkBoxCommonFilter, self.checkBoxGraphCPU)
        ProvWindow.setTabOrder(self.checkBoxGraphCPU, self.checkBoxGraphMem)
        ProvWindow.setTabOrder(self.checkBoxGraphMem, self.checkBoxGraphIO)
        ProvWindow.setTabOrder(self.checkBoxGraphIO, self.checkBoxGraphThread)
        ProvWindow.setTabOrder(self.checkBoxGraphThread, self.checkBoxGraphNetwork)
        ProvWindow.setTabOrder(self.checkBoxGraphNetwork, self.lineEdit_3)
        ProvWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        ProvWindow.setTabOrder(self.lineEdit_4, self.plainTextEdit)
        ProvWindow.setTabOrder(self.plainTextEdit, self.tableWidget)
        ProvWindow.setTabOrder(self.tableWidget, self.pushButtonReExecute)
        ProvWindow.setTabOrder(self.pushButtonReExecute, self.pushButtonResetFilter)
        ProvWindow.setTabOrder(self.pushButtonResetFilter, self.pushButtonRestoreFilter)
        ProvWindow.setTabOrder(self.pushButtonRestoreFilter, self.graphTab)
        ProvWindow.setTabOrder(self.graphTab, self.pushButtonBack)
        ProvWindow.setTabOrder(self.pushButtonBack, self.pushButtonForward)
        ProvWindow.setTabOrder(self.pushButtonForward, self.graph)
        ProvWindow.setTabOrder(self.graph, self.tab)
        ProvWindow.setTabOrder(self.tab, self.contentGraph)
        ProvWindow.setTabOrder(self.contentGraph, self.pushButtonEnableEditor)
        ProvWindow.setTabOrder(self.pushButtonEnableEditor, self.lineEdit)
        ProvWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        ProvWindow.setTabOrder(self.lineEdit_2, self.fullStatsGraph)

    def retranslateUi(self, ProvWindow):
        ProvWindow.setWindowTitle(_translate("ProvWindow", "MainWindow", None))
        self.label.setText(_translate("ProvWindow", "Graph Depth", None))
        self.checkBoxShowAll.setText(_translate("ProvWindow", "Show All", None))
        self.label_2.setText(_translate("ProvWindow", "Display", None))
        self.checkBoxShowFile.setText(_translate("ProvWindow", "Files", None))
        self.checkBoxShowProc.setText(_translate("ProvWindow", "Processes", None))
        self.label_3.setText(_translate("ProvWindow", "Highlight", None))
        self.checkBoxCommonFilter.setText(_translate("ProvWindow", "Enable Common Filter", None))
        self.checkBoxTempFilter.setText(_translate("ProvWindow", "Enable Highlighter", None))
        self.lineEditTempFilter.setToolTip(_translate("ProvWindow", "Any node matched pattern \".*{input}.*\" will be highlighted", None))
        self.content.setText(_translate("ProvWindow", "TextLabel", None))
        self.pushButtonEnableEditor.setText(_translate("ProvWindow", "Show Re-execution Editor", None))
        self.tab.setTabText(self.tab.indexOf(self.mainTab), _translate("ProvWindow", "Main", None))
        self.label_5.setText(_translate("ProvWindow", "Parent Pid", None))
        self.label_6.setText(_translate("ProvWindow", "Pid", None))
        self.label_7.setText(_translate("ProvWindow", "Path", None))
        self.label_8.setText(_translate("ProvWindow", "Working Dir", None))
        self.label_9.setText(_translate("ProvWindow", "Parameters", None))
        self.label_10.setText(_translate("ProvWindow", "Input Files", None))
        self.pushButtonReExecute.setText(_translate("ProvWindow", "Execute", None))
        self.tab.setTabText(self.tab.indexOf(self.editTab), _translate("ProvWindow", "Re-execution Editor", None))
        self.label_4.setText(_translate("ProvWindow", "Filters", None))
        self.pushButtonResetFilter.setText(_translate("ProvWindow", "Reset Default", None))
        self.pushButtonSaveFilter.setText(_translate("ProvWindow", "Save", None))
        self.pushButtonRestoreFilter.setText(_translate("ProvWindow", "Restore", None))
        self.tab.setTabText(self.tab.indexOf(self.filterTab), _translate("ProvWindow", "Common Filters", None))
        self.pushButtonBack.setText(_translate("ProvWindow", "&Back", None))
        self.pushButtonForward.setText(_translate("ProvWindow", "&Forward", None))
        self.graphTab.setTabText(self.graphTab.indexOf(self.provTab), _translate("ProvWindow", "Provenance Graph", None))
        self.checkBoxGraphCPU.setText(_translate("ProvWindow", "CPU", None))
        self.checkBoxGraphMem.setText(_translate("ProvWindow", "Mem", None))
        self.checkBoxGraphIO.setText(_translate("ProvWindow", "I/O", None))
        self.checkBoxGraphThread.setText(_translate("ProvWindow", "Thread", None))
        self.checkBoxGraphNetwork.setText(_translate("ProvWindow", "Network", None))
        self.graphTab.setTabText(self.graphTab.indexOf(self.statsTab), _translate("ProvWindow", "Stats", None))
        self.menuFile.setTitle(_translate("ProvWindow", "File", None))
        self.menuView.setTitle(_translate("ProvWindow", "View", None))
        self.menuSettings.setTitle(_translate("ProvWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("ProvWindow", "Help", None))
        self.menuProvenance.setTitle(_translate("ProvWindow", "Provenance", None))
        self.actionOpen.setText(_translate("ProvWindow", "Open PDF ...", None))
        self.actionOpen.setShortcut(_translate("ProvWindow", "Ctrl+O", None))
        self.actionClose.setText(_translate("ProvWindow", "Close", None))
        self.actionClose.setShortcut(_translate("ProvWindow", "Ctrl+W", None))
        self.action.setText(_translate("ProvWindow", "---", None))
        self.actionQuit.setText(_translate("ProvWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("ProvWindow", "Ctrl+Q", None))
        self.actionHelp.setText(_translate("ProvWindow", "Help", None))
        self.actionAbout.setText(_translate("ProvWindow", "About", None))
        self.action_SOLE.setText(_translate("ProvWindow", "&SOLE", None))
        self.action_PTU.setText(_translate("ProvWindow", "&PTU", None))
        self.action_GUI.setText(_translate("ProvWindow", "&GUI", None))
        self.actionRefresh.setText(_translate("ProvWindow", "Refresh", None))
        self.actionBack.setText(_translate("ProvWindow", "Go &Back", None))
        self.actionBack.setShortcut(_translate("ProvWindow", "Alt+Left", None))
        self.actionForward.setText(_translate("ProvWindow", "Go &Forward", None))
        self.actionForward.setShortcut(_translate("ProvWindow", "Alt+Right", None))
        self.actionOpen_Provenance.setText(_translate("ProvWindow", "Open Provenance...", None))
        self.actionOpen_Provenance.setShortcut(_translate("ProvWindow", "Ctrl+Shift+O", None))
        self.actionCopy_ID.setText(_translate("ProvWindow", "Copy ID", None))
        self.actionCopy_ID.setShortcut(_translate("ProvWindow", "Ctrl+Shift+C", None))

from pyqtgraph import PlotWidget
from graphwidget import GraphWidget
